name: Deployment

on:
  push:
    branches:
      - master

jobs:

  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: "Init: Summon NodeJS"
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: "Cache: node_modules"
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-${{ env.cache-name }}-
          ${{ runner.OS }}-node-
    - name: "Init: Install dependencies"
      run: |
        npm install
    - name: "Test: Code linting"
      run: |
        npm run lint
  deploy:
    needs: test
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: 'Init: Summon NodeJS'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Cache: node_modules"
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-${{ env.cache-name }}-
            ${{ runner.OS }}-node-
      - name: 'Init: Install dependencies'
        run: |
          npm install
      - name: "Build: Build static Next site"
        env:
          FULLSTORY: ${{ secrets.FULLSTORY }}
        run: |
          npm run build
          npm run export
      - name: "Deploy: Upload to Firebase"
        env:
          FIREBASE_DEPLOY_KEY: ${{ secrets.FIREBASE_DEPLOY_KEY }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          npm run firebase deploy -m "Automatic deployment from GitHub Actions" --non-interactive --token $FIREBASE_DEPLOY_KEY --project $FIREBASE_PROJECT_ID
